### ISSUE TITLE
Removal of BinOC Assets

### ISSUE THREAD

**Issue by mattatobin** [royalgeekworld/royalgeekworld.github.io#13]
Please remove the following BinOC Assets or I will file a DMCA against the entire repository.

The Icon for this organization, The BinOC/Network Event Hall Image, and you should likely get a new wordmark but I am unconcerned about it.

You have until the end of next week to comply with this request.

**Comment by mattatobin** [comment]
@Conan-Kudo

**Comment by Conan-Kudo** [comment]
This is done.
